/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zootopia;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Varian Caesar / 13514041
 * @author Ade Yusuf Rahardian / 13514037
 */
public class Zootopia extends javax.swing.JFrame {

    /**
     * Creates new form Zootopia
     */
    public Zootopia() {
        initComponents();
        String banner = "<html><pre>====================================================================== <br> "
                + "       HHHHHHH   HHHHH  HHHHH HHHHHH  HHHHH HHHHH  HHH  HHH     <br>"
                + "            HH   HH  HH HH  HH   HH   HH  HH HH  HH HH  HH HH         <br>"
                + "          HHH    H    H H    H   HH   H    H HHHHH  H  HH   HH        <br>"
                + "         HH      HH  HH HH  HH   HH   HH  HH HH    HH  HHHHHHH        <br>"
                + "        HHHHHHH  HHHHH  HHHHH    HH   HHHHH  H    HHH  HH   HH        <br>"
                + "======================================================================<br> </pre></html>";
        jLabel1.setText(banner);
        addKeyListener(new KeyPress());
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExitButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExitButton.setText("exit");
        ExitButton.setName("ExitButton"); // NOI18N
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        StartButton.setText("Start");
        StartButton.setName("Start"); // NOI18N
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("nanti dihapus ini");

        jLabel2.setText("Masukan ukuran dunia (>= 3) :");

        jLabel3.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExitButton)
                            .addComponent(StartButton)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExitButton)
                        .addGap(232, 232, 232))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        JFrame view = new JFrame();
        JPanel panel = new JPanel();
        JLabel label1 = new JLabel();
        JLabel label2 = new JLabel();
        JLabel label3 = new JLabel();
        //Menambah Komponen
        panel.add(label1);
        panel.add(label2);
        panel.add(label3);
        view.add(panel);
        view.setSize(1000,1000);
        view.addKeyListener(new KeyPress());
        view.setVisible(true);
        view.setAlwaysOnTop(true);
        jLabel3 = label1;
        jLabel4 = label2;
        jLabel5 = label3;
        // TODO add your handling code here: 
        int i,j;
        int check = Integer.parseInt(jTextField1.getText());
        worldSize = check;
        startMakhluk = worldSize * worldSize / RATIO_MAKHLUK;
        w = new World(worldSize);
        endworld = false;
        stop = false;
        frameByFrame = false;
        wait = DELTA_TIME;

        for (i = 0; i < startMakhluk; i++) {
            w.createMakhluk();
        }

        LabelChanger l = new LabelChanger();
        Thread t = new Thread(l);
        t.start();      
    }//GEN-LAST:event_StartButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        endworld = true;
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zootopia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zootopia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zootopia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zootopia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Zootopia().setVisible(true);
        });
    }
    public static boolean getEndworld() {
        return endworld;
    }
    public static void setEndworld(boolean v) {
        endworld = v;
    }
    public static boolean getStop() {
        return stop;
    }
    public static void setStop(boolean v) {
        stop = v;
    }
    public static boolean getFrameByFrame() {
        return frameByFrame;
    }
    public static void setFrameByFrame(boolean v) {
        frameByFrame = v;
    }
    public static int getWait() {
        return wait;
    }
    public static void setWait(int v) {
        wait = v;
    }
    public static int getDeltaTime() {
        return DELTA_TIME;
    }
    public static int getWorldSize() {
        return worldSize;
    }
    public static World getWorld() {
        return w;
    }
    public javax.swing.JLabel getLabel3() {
        return jLabel3;
    }
    public javax.swing.JLabel getLabel4() {
        return jLabel4;
    }
    public javax.swing.JLabel getLabel5() {
        return jLabel5;
    }
    public static char getbufferDirection() {
        return bufferDirection;
    }
    public static void setbufferDirection(char c) {
        bufferDirection = c;
    }
    
    private static final int RATIO_MAKHLUK = 50;
    private static boolean endworld;
    private static final int SCREEN_SIZE = 20;
    private static int worldSize;
    private static int startMakhluk;
    private static final int DELTA_TIME = 100;
    private static World w;
    private static boolean stop;
    private static boolean frameByFrame;
    private static int wait;
    private static char bufferDirection = 'N'; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
